site_name: Grupo 1

repo_name: '2022.2-Grupo1'
repo_url: 'https://github.com/Interacao-Humano-Computador/2022.2-Grupo1'

copyright: 'Copyright &copy; 2022 Grupo 1'

theme:
  name: material
  language: 'pt'
  palette:
    primary: deep purple
    accent: orange
  font:
    text: 'Montserrat'
    code: 'sans-serif'

nav:
  - Início: index.md
  - Planejamento:
    - Reuniões: planning/reunioes.md
    - Metodologia: planning/metodologia.md
