site_name: Skoob

repo_name: "2022.2-Skoob"
repo_url: "https://github.com/Interacao-Humano-Computador/2022.2-Skoob"

copyright: "Copyright &copy; 2022 Grupo 1"

theme:
  name: material
  language: "pt"
  palette:
    primary: light blue
    accent: white
  features:
    - navigation.tabs
  font:
    text: "Montserrat"
    code: "sans-serif"
  logo: assets/logo.png
  favicon: assets/logo.png
nav:
  - Início: index.md
  - Planejamento:
      - Reuniões: planejamento/reunioes.md
      - Metodologia: planejamento/metodologia.md
      - Ferramentas: planejamento/ferramentas.md
      - Processo Design: planejamento/processoDesign.md
      - Cronograma: planejamento/cronograma.md
      - Lista de Sites Avaliados: planejamento/SitesAvaliados.md
  - Análise de Requisitos:
      - Análise de Tarefas:
        - Árvores de Tarefas Concorrentes: analise-de-requisitos/analise-de-tarefas-concorrentes.md
        - Análise Hierárquica de tarefas: analise-de-requisitos/analisehierarquicadetarefas.md
      - Aspectos Éticos: analise-de-requisitos/aspectos-eticos.md
      - Perfil do Usuário: analise-de-requisitos/perfil-do-usuario.md
      - Personas: analise-de-requisitos/personas.md
      - Caract. da Plataforma: analise-de-requisitos/caracteristicas-da-plataforma.md
      - Metas de Usabilidade: analise-de-requisitos/metas-usabilidade.md
      - Principios Gerais de Projeto: analise-de-requisitos/principios-gerais-de-projeto.md
      - Guia de Estilo: analise-de-requisitos/guia-de-estilo.md
  - Atas das Reuniões:
      - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 17/11/2022: atas-das-reunioes/reuniao2.md
      - Reunião 3 - 29/11/2022: atas-das-reunioes/reuniao3.md
      - Reunião 4 - 06/12/2022: atas-das-reunioes/reuniao4.md
  - Apresentações:
      - Etapa 1 - 23/11: apresentacoes/etapa1.md
      - Etapa 2 - 07/12: apresentacoes/etapa2.md
