site_name: Skoob

repo_name: "2022.2-Skoob"
repo_url: "https://github.com/Interacao-Humano-Computador/2022.2-Skoob"

copyright: "Copyright &copy; 2022 Grupo 1"

theme:
  name: material
  language: "pt"
  palette:
    primary: light blue
    accent: white
  features:
    - navigation.tabs
  font:
    text: "Montserrat"
    code: "sans-serif"
  logo: assets/logo.png
  favicon: assets/logo.png
nav:
  - Início: index.md
  - Planejamento:
      - Reuniões: planejamento/reunioes.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Cronograma: planejamento/cronograma.md

  - Atas das Reuniões:
      - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
      - Reunião 2 - 17/11/2022: atas-das-reunioes/reuniao2.md
