site_name: CAPES

repo_name: '2022.2-CAPES'
repo_url: 'https://github.com/Interacao-Humano-Computador/2022.2-CAPES'

copyright: 'Copyright &copy; 2022 Grupo 1'

theme:
  name: material
  language: 'pt'
  palette:
    primary: light blue
    accent: green
  features:
    - navigation.tabs
  font:
    text: 'Montserrat'
    code: 'sans-serif'

nav:
  - Início: index.md
  - Planejamento:
    - Reuniões: planejamento/reunioes.md
    - Metodologia: planejamento/metodologia.md
  - Atas das Reuniões:
    - Reunião 1 - 15/11/2022: atas-das-reunioes/reuniao1.md
